//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBP2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautySalonContainer : DbContext
    {
        public BeautySalonContainer()
            : base("name=BeautySalonContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manufacturer> ManufacturerSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Owner> OwnerSet { get; set; }
        public virtual DbSet<Shift> ShiftSet { get; set; }
        public virtual DbSet<Job> JobSet { get; set; }
        public virtual DbSet<Worker> WorkerSet { get; set; }
        public virtual DbSet<Bill> BillSet { get; set; }
        public virtual DbSet<Service> ServiceSet { get; set; }
        public virtual DbSet<Boss> BossSet { get; set; }
        public virtual DbSet<ServiceCompany> ServiceCompanySet { get; set; }
        public virtual DbSet<Work> WorkSet { get; set; }
        public virtual DbSet<Appoitment> AppoitmentSet { get; set; }
        public virtual DbSet<Sector> SectorSet { get; set; }
        public virtual DbSet<Collaborate> CollaborateSet { get; set; }
    }
}
